- hosts: 'workers, masters'
  become: yes

  tasks:
    - name: create the kube user account
      user:
        name: kube
        append: yes
        state: present
        create_home: yes
        shell: /bin/bash

    - name: allow 'kube' to use sudo without needing a password
      lineinfile:
        dest: /etc/sudoers
        line: 'kube ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: set up authorized keys for the kube user
      authorized_key:
        user: kube
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
